### ISSUE TITLE
Please release 1.0.4

### ISSUE THREAD

**Issue by askldjd** [oliverwoodings/pkgify#12]
I am currently developing on Windows and I am seeing the bug on windows path that you have patched 5 month ago. Would you please tag a new version and publish a new version in NPM?

Thanks

... Alan

**Comment by oliverwoodings** [comment]
Hi, that patch was released, it was version 1.0.3. There is no 1.0.4 to be released. Someone created a PR a while back (https://github.com/oliverwoodings/pkgify/pull/11) which apparently fixed it on windows, but I have not been able to test it. Could you give that PR a try and let me know if it works? If it does I'll merge it.

**Comment by askldjd** [comment]
The PR works. I tested it in my codebase and pkgify completed the transformation that previously failed in 1.0.3.

Thanks

... Alan

**Comment by oliverwoodings** [comment]
Merged, released as 1.1.0
